### ISSUE TITLE
Suggest a modification to an otherwise great module

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-simple-menu#1]
Hi JustCarmen,

I would like to make a suggestion to make a slight modification to the otherwise great simple-menu module.

The content page for a menu item does not adjust to changed width of a page when a code is added in the CSS & JS module to globally change the width of all content pages, see inserted code: `<style> .container, .container-lg, .container-md, .container-sm, .container-xl, .container-fluid { max-width: 90% } </style>`. Content pages of other modules like, FAQ, Stories and others adjust easily to this change in the CSS & JS module.

I managed to find a temporary solution by changing this directly in the code of the simple-menu module to a suitable width in page.phtml `<div class="jc-simple-menu-page col-lg-9 mx-auto”>` to `<div class="jc-simple-menu-page col-xl-12 mx-auto">`.

It would be better if the current code of simple-menu module could be changed so that when inserting a code in CSS & JS module to change page content width that it would affect all the modules of webtreees equally.

Hopefully this explains my suggestsion for a modification to the simple-menu module.

**Comment by mpwt** [comment]
> I managed to find a temporary solution by changing this directly in the code of the simple-menu module to a suitable width in page.phtml `<div class="jc-simple-menu-page col-lg-9 mx-auto”>` to `<div class="jc-simple-menu-page col-xl-12 mx-auto">`.

I have already changed this in v1.0 as follows: `<div class="jc-simple-menu-page col-md-12 mx-auto">`. At that time, it was the same formatting as on other pages.

**Comment by gudjonsi** [comment]
Thanks, I just downloaded v1.1 and it still contains the old code and viewing the page.phtml code on Github it also appears unchanged, see image. Maybe I’m missing something here.
![43F9A089-DACF-4E90-9A9F-C8697F5EAA5C](https://user-images.githubusercontent.com/100283838/191212377-c44d85a7-5f97-4b86-a07f-41b52163f32a.png)
